package com.quran.learnedplayer.data

/**
 * Reciters available from everyayah.com.
 *
 * The list is deliberately short: word-by-word highlighting is only honest when we have real
 * per-word timings for that exact recording, so we ship only reciters that QUL has segment data
 * for **and** whose everyayah audio is the audio those timings describe. Adding a reciter without
 * timings would mean guessing at word boundaries, so don't.
 *
 * QUL does not name its reciters, so the id behind each asset was pinned by measurement rather
 * than by trusting a label: the last segment of an ayah has to end where everyayah's MP3 for that
 * reciter ends. Sudais (QUL 16) and Shuraym (QUL 25) land within 0-50ms across 1:1, 1:7, 2:255,
 * 112:1 and 112:2, the same band as the three that were already shipped. See `.setup/make_timings.py`.
 *
 * [folder] is everyayah's directory name and also the on-device audio cache directory, so each
 * reciter's downloads stay separate. [timingsAsset] is generated by `make_timings.py`.
 */
enum class Reciter(
    val displayName: String,
    val folder: String,
    val timingsAsset: String,
) {
    MAHER_AL_MUAIQLY(
        displayName = "Maher Al Muaiqly",
        folder = "MaherAlMuaiqly128kbps",
        timingsAsset = "word_timings_maher.json",
    ),
    ABDUL_BASIT(
        displayName = "Abdul Basit (Murattal)",
        folder = "Abdul_Basit_Murattal_192kbps",
        timingsAsset = "word_timings_abdulbasit_murattal.json",
    ),
    AL_HUSARY(
        displayName = "Mahmoud Khalil Al-Husary",
        folder = "Husary_128kbps",
        timingsAsset = "word_timings_husary.json",
    ),
    AS_SUDAIS(
        displayName = "Abdurrahman As-Sudais",
        folder = "Abdurrahmaan_As-Sudais_192kbps",
        timingsAsset = "word_timings_sudais.json",
    ),
    ASH_SHURAYM(
        displayName = "Saud Ash-Shuraym",
        folder = "Saood_ash-Shuraym_128kbps",
        timingsAsset = "word_timings_shuraym.json",
    ),
    ;

    companion object {
        val DEFAULT = MAHER_AL_MUAIQLY

        fun fromKey(key: String?): Reciter = entries.firstOrNull { it.name == key } ?: DEFAULT
    }
}
